package org.roly.personalaccountant.services;

import static org.assertj.core.api.Assertions.assertThat;

import org.jooq.DSLContext;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.roly.personalaccountant.domain.model.services.CategoryService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * The {@code category} table has no JPA entity (by design), and Flyway is disabled in the test profile, so Hibernate's {@code create-drop} never
 * creates it. We therefore provision and seed the table ourselves around each test. {@code @SpringBootTest} is intentionally non-transactional here:
 * H2 auto-commits DDL, which would break a rollback-based slice such as {@code @JooqTest}.
 */
@SpringBootTest
class CategoryServiceTest {

    @Autowired
    private CategoryService categoryService;

    @Autowired
    private DSLContext dsl;

    @BeforeEach
    void setUp() {
        dsl.execute("""
                create table if not exists category (
                    id       bigint generated by default as identity,
                    name     varchar(255)          not null,
                    archived boolean default false not null,
                    primary key (id),
                    unique (name)
                )
                """);
        dsl.execute("delete from category");
        dsl.execute("insert into category (name) values ('Food'), ('Media'), ('Etf')");
        dsl.execute("insert into category (name, archived) values ('Archived one', true)");
    }

    @AfterEach
    void tearDown() {
        dsl.execute("drop table if exists category");
    }

    @Test
    void listActiveReturnsNonArchivedNamesSortedAlphabetically() {
        assertThat(categoryService.listActive()).containsExactly("Etf", "Food", "Media");
    }

    @Test
    void listActiveExcludesArchivedCategories() {
        assertThat(categoryService.listActive()).doesNotContain("Archived one");
    }

    @Test
    void addIfAbsentInsertsANewCategory() {
        categoryService.addIfAbsent("Travel");

        assertThat(categoryService.listActive()).contains("Travel");
    }

    @Test
    void addIfAbsentIsIdempotentAndCaseInsensitive() {
        categoryService.addIfAbsent("food");
        categoryService.addIfAbsent("  FOOD ");

        long foodCount = categoryService.listActive().stream()
                .filter(c -> c.equalsIgnoreCase("food"))
                .count();
        assertThat(foodCount).isEqualTo(1);
    }

    @Test
    void addIfAbsentTrimsWhitespace() {
        categoryService.addIfAbsent("  Garden  ");

        assertThat(categoryService.listActive()).contains("Garden");
    }

    @Test
    void addIfAbsentIgnoresNullAndBlank() {
        categoryService.addIfAbsent(null);
        categoryService.addIfAbsent("   ");

        assertThat(categoryService.listActive()).containsExactly("Etf", "Food", "Media");
    }

    @Test
    void archiveRemovesCategoryFromActiveList() {
        categoryService.archive("Food");

        assertThat(categoryService.listActive()).doesNotContain("Food");
    }
}
