-- Baseline schema for personal-accountant.
-- Generated from Hibernate entity metadata (H2 dialect). Enum-typed columns (category, type)
-- are stored as VARCHAR to match spring.jpa.properties.hibernate.type.preferred_enum_jdbc_type=VARCHAR.
-- This runs only on a fresh/empty database; existing databases are baselined at V1 (see
-- spring.flyway.baseline-on-migrate).

create table income_entity
(
    date               date,
    income_value       float(53),
    id                 bigint generated by default as identity,
    monthly_expense_id bigint,
    source             varchar(255),
    primary key (id)
);

create table monthly_expense_entity
(
    end_date       date,
    expense_month  integer,
    expense_year   integer,
    fixed_budget   float(53) default 0 not null,
    leisure_budget float(53) default 0 not null,
    saving_budget  float(53) default 0 not null,
    start_date     date,
    id             bigint generated by default as identity,
    expense_name   varchar(255),
    primary key (id),
    unique (expense_year, expense_month)
);

create table monthly_expense_entity_done_days
(
    done_days                 date,
    monthly_expense_entity_id bigint not null
);

create table payment_entity
(
    amount             float(53),
    date               date,
    id                 bigint generated by default as identity,
    monthly_expense_id bigint,
    description        varchar(255),
    category           varchar(255),
    type               varchar(255),
    primary key (id)
);

create table pending_payment_entity
(
    amount             float(53) not null,
    id                 bigint generated by default as identity,
    monthly_expense_id bigint,
    name               varchar(255),
    category           varchar(255),
    type               varchar(255),
    primary key (id)
);

create table recurring_payment_template
(
    default_amount float(53) not null,
    id             bigint generated by default as identity,
    name           varchar(255),
    category       varchar(255),
    type           varchar(255),
    primary key (id)
);

create table saving_entity
(
    percentage         float(53) not null,
    id                 bigint generated by default as identity,
    monthly_expense_id bigint,
    name               varchar(255),
    primary key (id)
);

alter table if exists income_entity
    add constraint FKhw6gek64alt5ufw772ogwo0tc foreign key (monthly_expense_id) references monthly_expense_entity;
alter table if exists monthly_expense_entity_done_days
    add constraint FK6freybibb4es346gab8hqp47y foreign key (monthly_expense_entity_id) references monthly_expense_entity;
alter table if exists payment_entity
    add constraint FKklypfcovtkic0okf7e4gw2ggo foreign key (monthly_expense_id) references monthly_expense_entity;
alter table if exists pending_payment_entity
    add constraint FKojobcmcksobhamvwv8grsdadr foreign key (monthly_expense_id) references monthly_expense_entity;
alter table if exists saving_entity
    add constraint FK76o3r0sebct8l7ekfx7tejv4q foreign key (monthly_expense_id) references monthly_expense_entity;
