-- Category lookup table to replace the compile-time Category enum.
create table category
(
    id       bigint generated by default as identity,
    name     varchar(255)          not null,
    archived boolean default false not null,
    primary key (id),
    unique (name)
);

-- Seed the 23 current categories using the existing getDisplayName() convention:
-- underscores become spaces and only the first letter is capitalised
-- (e.g. PAY_OFF -> 'Pay off', CREDIT_CARD -> 'Credit card').
-- IDs are auto-assigned so the identity sequence stays correct for later
-- "add category on the fly" inserts.
insert into category (name)
values ('Food'),
       ('Media'),
       ('Invoice'),
       ('Insurance'),
       ('Health'),
       ('Fuel'),
       ('Travel'),
       ('Vacation'),
       ('Telco'),
       ('Fun'),
       ('Gift'),
       ('Etf'),
       ('Pay off'),
       ('Garden'),
       ('House'),
       ('Other'),
       ('Tobacco'),
       ('Clothes'),
       ('Mortgage'),
       ('Leasing'),
       ('Cat'),
       ('Electricity'),
       ('Credit card');
